
osx_image: xcode9.1
language: swift
os: osx

xcode_workspace: AnyFormatKit.xcworkspace
xcode_scheme: 
  - AnyFormatKit
  - AnyFormatKitTests
  - iOS Example

branches:
  only:
    - master
    - develop

script: ./run-tests.sh

notifications:
  email:
    - luximetr.notification@gmail.com