
osx_image: xcode9
language: swift

xcode_workspace: AnyFormatKit.xcworkspace
xcode_scheme: 
  - AnyFormatKit
  - AnyFormatKitTests
  - iOS Example

branches:
  only:
    - SumFormatting

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - nvm install 7
  - npm install -g yarn xvfb-maybe
  - yarn
script:
  - xvfb-maybe node_modules/.bin/karma start test/unit/karma.conf.js
  - yarn run pack && xvfb-maybe node_modules/.bin/mocha test/e2e  

